name: jiamei_employee_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # Http请求库
  dio: ^3.0.8
  fluro: ^1.5.1
  fluttertoast: ^3.1.3
  # 适应
  flutter_screenutil: ^3.1.0
  # 状态管理
  provide: ^1.0.2
  # 储存
  shared_preferences: ^0.5.5
  # 颜色插件
  flutter_color_plugin: ^0.0.2
  # 手机权限
  permission_handler: ^4.4.0
  # 定位
  #  amap_location_fluttify: ^0.20.0
  #  core_location_fluttify: ^0.6.0
  amap_location_fluttify: 0.8.11+481e45c
  # 数据加载中
  flutter_spinkit: ^4.0.0
  # picker 选择器
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_picker: ^1.1.0
  # 格式化日期
  date_format: ^1.0.8
  # 图片上传
  image_picker: ^0.6.3+4
  # 图片预览
  photo_view: ^0.9.2
  # 跳转
  url_launcher: ^5.1.1
  # 日期时间数据格式化
  common_utils: ^1.1.1
  # 验证码框
  flutter_verification_box: ^1.0.3
  # 评分
  spon_rating_bar: ^0.0.1
  # 多语言
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  # 数据model层
  json_model: 0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/images/login_logo.png
    - lib/images/no_list.png
    - lib/images/my_bg.png
    - lib/images/work_banner.png
    - lib/images/splash_bg.png
    - lib/images/no_leave.png
    - lib/images/work_detail.png
    - lib/images/date1.png
    - lib/images/date2.png
    - lib/images/date3.png
    - lib/images/message_icon1.png
    - lib/images/no_message_list.png
    - lib/images/service_detail_bg.png
    - lib/images/login_text.png
    - lib/images/photo_img.png
    - lib/images/icons/home_icon.png
    - lib/images/icons/my.png
    - lib/images/icons/my_active.png
    - lib/images/icons/home.png
    - lib/images/icons/home_active.png
    - lib/images/icons/icon-minus.png
    - lib/images/icons/icon-plus.png
    - lib/images/icons/workbench.png
    - lib/images/icons/workbench_active.png
    - lib/images/icons/call_phone_icon.png
    - lib/images/icons/time_icon.png
    - lib/images/icons/time_icon2.png
    - lib/images/icons/time_icon3.png
    - lib/images/icons/to_navigate_icon.png
    - lib/images/icons/star.png
    - lib/images/icons/star_nomal.png
    - lib/images/icons/work_icon1.png
    - lib/images/icons/work_icon2.png
    - lib/images/icons/cart_icon.png
    - lib/images/icons/del_photo_icon.png
    - lib/images/icons/my_right_icon.png
    - lib/images/icons/close_icon.png
    - lib/images/icons/feedback_icon.png
    - lib/images/icons/set_up_icon.png
    - lib/images/icons/work_icon3.png
    - lib/images/icons/work_icon4.png
    - lib/images/icons/sel_icon.png
    - lib/images/icons/sel_right_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
